# Generated by Django 5.0 on 2024-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[(1, 'dairy & poultry'), (2, 'meat'), (3, 'farm produce'), (4, 'natural superfoods')], default=1),
        ),
    ]
