# Generated by Django 5.0.1 on 2024-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_checkout_date_checkout_pincode_checkout_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
