# Generated by Django 5.0 on 2024-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
