# Generated by Django 5.0 on 2024-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[(1, 'dairy'), (2, 'meat'), (3, 'burger')], default=1),
        ),
    ]
