# Generated by Django 5.0.1 on 2024-02-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
