# Generated by Django 5.0 on 2024-02-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
